name: manylinux

# Builds the manylinux2014 image
# See https://github.com/pypa/manylinux/blob/main/.github/workflows/build.yml

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'colesbury/manylinux'
          ref: nogil

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: |
          PLATFORM=$(uname -m) POLICY=manylinux2014 PYTHON_VERSION=3.9.10 COMMIT_SHA=$GITHUB_SHA ./build.sh
          docker tag nogil/manylinux2014_x86_64:$GITHUB_SHA nogil/manylinux2014_x86_64:latest
          docker push nogil/manylinux2014_x86_64:$GITHUB_SHA
          docker push nogil/manylinux2014_x86_64:latest
